### ISSUE TITLE
electron dependency is missing

### ISSUE THREAD

**Issue by GEESIGNZ** [carloslfu/figma-app-linux#13]
Hello.

I have the following error:

```
ERR! stack Error: 404 response downloading https://atom.io/download/electron/v8.9.3/node-v8.9.3-headers.tar.gz
```

Probably the electron dependency is missing.

**Comment by carloslfu** [comment]
Thanks, it is fixed now via https://github.com/carloslfu/figma-app-linux/commit/d6498c19fa1c1bf7adcd9b36b08294cc29528565.
