### ISSUE TITLE
Latest Figma broke the app

### ISSUE THREAD

**Issue by hezral** [carloslfu/figma-app-linux#14]
![image](https://user-images.githubusercontent.com/762735/51316711-714d1280-1a90-11e9-9106-a249491b2830.png)

Could you update the app?

**Comment by kobuta23** [comment]
same here!

**Comment by 0x4139** [comment]
any status?

**Comment by semonje** [comment]
Same here :sob:

**Comment by jackbillstrom** [comment]
Because of this I just decided to make my own build that works meanwhile, chekout my own homebrew here if you'd need Figma up and running without buildning it from the source yourselves.

https://github.com/jackbillstrom/figma-app-linux/releases/tag/68.5.0

**Comment by hezral** [comment]
What do you mean by not binding? And does your build support local font

**Comment by hezral** [comment]
Just tested it out, there are some spacing issues on left and right and also its not using the GTK window decorations. 

i'm on elementary OS 5 Juno

![image](https://user-images.githubusercontent.com/762735/51794878-b6064580-2216-11e9-959f-2da9ba74a3d8.png)

**Comment by jackbillstrom** [comment]
@hezral I've noticed this as well, will be looking into this during the weekend.

But I'm quite used to using `Alt + Spacebar` (for those who don't know to manage their borderless window)

**Comment by carloslfu** [comment]
Updated release [here](https://github.com/carloslfu/figma-app-linux/releases/download/v3/Figma-68.5.0-x86_64.AppImage). Thanks @jackbillstrom and @hezral.

**Comment by YouTwitFace** [comment]
@carloslfu thanks.

**Comment by hezral** [comment]
Awesome, will check when i get home.

**Comment by semonje** [comment]
'

**Comment by hezral** [comment]
Same here. Was there a change on how the app is compiled? it used to have the window decorations before but now it's just the app frame. Still usable, just wondering what changed.
